version: "3"
services:
    composer:
        restart: "no"
        image: "composer:latest"
        working_dir: "/app"
        volumes:
            - ".:/app"
        command: "install"
    php:
        build:
            context: "."
            dockerfile: ".docker/php/Dockerfile"
        working_dir: "/app"
        volumes:
            - ".:/app"
        command: "php -S 0.0.0.0:${PORT_PHP} -t public"
        ports:
            - "${PORT_PHP}:${PORT_PHP}"
        environment:
            DATABASE_URL: "mysql://user:password@mysql:3306/main"
    mysql:
        image: "mysql:5.7"
        expose:
            - "3306"
        ports:
            - "${PORT_MYSQL}:3306"
        volumes:
          - ".docker/data/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "rootpassword"
            MYSQL_DATABASE: "main"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
